#!/bin/bash
sudo yum update -y
sudo amazon-linux-extras install epel -y 
sudo yum install https://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm -y
sudo yum install mysql-community-server -y
systemctl active mysqld 
systemctl start mysqld